### ISSUE TITLE
feature: support per-user default hunspell dictionary

### ISSUE THREAD

**Issue by philpennock** [kortschak/gospel#2]
This is for `~/.hunspell_en_US` (documented in the manual page as `~/.hunspell_default`).  This isn't quite documented right, but the goal for gospel would be to just share the dictionary in practice.

Inside hunspell's git repo, `src/tools/hunspell.cxx` inside `main()` has, starting at line 2120 as of hunspell/hunspell@31e6d6323 :

```C++ linenos:true start:2120
  if (HOME) {
    buf.assign(HOME);
#ifndef WIN32
    buf.append("/");
#endif
    buf.append(DICBASENAME);
    buf.append(basename(dicname, DIRSEPCH));
    load_privdic(buf.c_str(), pMS[0]);
```

where `DICBASENAME` on not-WIN32 is `".hunspell_"` and `dicname` is derived in preceding `main()` logic to be the locale path, so ends `en_US` for American English speakers.

**Comment by kortschak** [comment]
Thinking more about this, I don't think this is a good fit for gospel; even having an language tag option allow potential confusion between participants in a project due to spelling differences and this is something that I'd like to fix by some option for a method of language pinning. I think the approach of per-module dictionaries better covers the flexibility needed while ensuring all of a project's contributors are in the same space (at the cost of the potential of file duplication).

**Comment by philpennock** [comment]
You're right.  I was thinking in terms of "my family name is already in my user dictionary, why would I need to flag it as not a spelling mistake here too", but the moment that a repo is edited by multiple people, _they'd_ all see my name highlighted as a spelling mistake.

So these should be either self-contained, or explicitly allowing for a workspace language if there are a _lot_ of common words.  But then, not everyone will be using a workspace, which opens the issue up again.  The best I've been able to think of is a reference to a repo containing just a dictionary, which then leads into tangled knots of how to correctly manage a single store of that and it's ... a design can of worms.  So, stick to self-contained, which leads to my opening statement: you're right.
